package com.backoffice.mapper;

import com.backoffice.model.Adminset;
import com.backoffice.model.AdminsetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminsetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    long countByExample(AdminsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int deleteByExample(AdminsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int insert(Adminset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int insertSelective(Adminset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    List<Adminset> selectByExample(AdminsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    Adminset selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") Adminset record, @Param("example") AdminsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByExample(@Param("record") Adminset record, @Param("example") AdminsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByPrimaryKeySelective(Adminset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByPrimaryKey(Adminset record);
}