package com.backoffice.mapper;

import com.backoffice.model.ExtratResult;
import com.backoffice.model.ExtratResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExtratResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extrat_result
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    long countByExample(ExtratResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extrat_result
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int deleteByExample(ExtratResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extrat_result
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extrat_result
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int insert(ExtratResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extrat_result
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int insertSelective(ExtratResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extrat_result
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    List<ExtratResult> selectByExample(ExtratResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extrat_result
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    ExtratResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extrat_result
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") ExtratResult record, @Param("example") ExtratResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extrat_result
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByExample(@Param("record") ExtratResult record, @Param("example") ExtratResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extrat_result
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByPrimaryKeySelective(ExtratResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extrat_result
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByPrimaryKey(ExtratResult record);
}