package com.backoffice.mapper;

import com.backoffice.model.SubjectGroupExpertOperate;
import com.backoffice.model.SubjectGroupExpertOperateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubjectGroupExpertOperateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group_expert_operate
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    long countByExample(SubjectGroupExpertOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group_expert_operate
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    int deleteByExample(SubjectGroupExpertOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group_expert_operate
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group_expert_operate
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    int insert(SubjectGroupExpertOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group_expert_operate
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    int insertSelective(SubjectGroupExpertOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group_expert_operate
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    List<SubjectGroupExpertOperate> selectByExample(SubjectGroupExpertOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group_expert_operate
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    SubjectGroupExpertOperate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group_expert_operate
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") SubjectGroupExpertOperate record, @Param("example") SubjectGroupExpertOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group_expert_operate
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    int updateByExample(@Param("record") SubjectGroupExpertOperate record, @Param("example") SubjectGroupExpertOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group_expert_operate
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    int updateByPrimaryKeySelective(SubjectGroupExpertOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group_expert_operate
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    int updateByPrimaryKey(SubjectGroupExpertOperate record);
}