package com.backoffice.mapper;

import com.backoffice.model.SubjectGroup;
import com.backoffice.model.SubjectGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubjectGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    long countByExample(SubjectGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int deleteByExample(SubjectGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int insert(SubjectGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int insertSelective(SubjectGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    List<SubjectGroup> selectByExample(SubjectGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    SubjectGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") SubjectGroup record, @Param("example") SubjectGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByExample(@Param("record") SubjectGroup record, @Param("example") SubjectGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByPrimaryKeySelective(SubjectGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    int updateByPrimaryKey(SubjectGroup record);
}