package com.backoffice.model;

import java.util.ArrayList;
import java.util.List;

public class AdminsetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public AdminsetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLogimgIsNull() {
            addCriterion("logimg is null");
            return (Criteria) this;
        }

        public Criteria andLogimgIsNotNull() {
            addCriterion("logimg is not null");
            return (Criteria) this;
        }

        public Criteria andLogimgEqualTo(String value) {
            addCriterion("logimg =", value, "logimg");
            return (Criteria) this;
        }

        public Criteria andLogimgNotEqualTo(String value) {
            addCriterion("logimg <>", value, "logimg");
            return (Criteria) this;
        }

        public Criteria andLogimgGreaterThan(String value) {
            addCriterion("logimg >", value, "logimg");
            return (Criteria) this;
        }

        public Criteria andLogimgGreaterThanOrEqualTo(String value) {
            addCriterion("logimg >=", value, "logimg");
            return (Criteria) this;
        }

        public Criteria andLogimgLessThan(String value) {
            addCriterion("logimg <", value, "logimg");
            return (Criteria) this;
        }

        public Criteria andLogimgLessThanOrEqualTo(String value) {
            addCriterion("logimg <=", value, "logimg");
            return (Criteria) this;
        }

        public Criteria andLogimgLike(String value) {
            addCriterion("logimg like", value, "logimg");
            return (Criteria) this;
        }

        public Criteria andLogimgNotLike(String value) {
            addCriterion("logimg not like", value, "logimg");
            return (Criteria) this;
        }

        public Criteria andLogimgIn(List<String> values) {
            addCriterion("logimg in", values, "logimg");
            return (Criteria) this;
        }

        public Criteria andLogimgNotIn(List<String> values) {
            addCriterion("logimg not in", values, "logimg");
            return (Criteria) this;
        }

        public Criteria andLogimgBetween(String value1, String value2) {
            addCriterion("logimg between", value1, value2, "logimg");
            return (Criteria) this;
        }

        public Criteria andLogimgNotBetween(String value1, String value2) {
            addCriterion("logimg not between", value1, value2, "logimg");
            return (Criteria) this;
        }

        public Criteria andSystemnameIsNull() {
            addCriterion("systemname is null");
            return (Criteria) this;
        }

        public Criteria andSystemnameIsNotNull() {
            addCriterion("systemname is not null");
            return (Criteria) this;
        }

        public Criteria andSystemnameEqualTo(String value) {
            addCriterion("systemname =", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotEqualTo(String value) {
            addCriterion("systemname <>", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameGreaterThan(String value) {
            addCriterion("systemname >", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameGreaterThanOrEqualTo(String value) {
            addCriterion("systemname >=", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLessThan(String value) {
            addCriterion("systemname <", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLessThanOrEqualTo(String value) {
            addCriterion("systemname <=", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLike(String value) {
            addCriterion("systemname like", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotLike(String value) {
            addCriterion("systemname not like", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameIn(List<String> values) {
            addCriterion("systemname in", values, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotIn(List<String> values) {
            addCriterion("systemname not in", values, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameBetween(String value1, String value2) {
            addCriterion("systemname between", value1, value2, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotBetween(String value1, String value2) {
            addCriterion("systemname not between", value1, value2, "systemname");
            return (Criteria) this;
        }

        public Criteria andDefaultnumIsNull() {
            addCriterion("defaultnum is null");
            return (Criteria) this;
        }

        public Criteria andDefaultnumIsNotNull() {
            addCriterion("defaultnum is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultnumEqualTo(Integer value) {
            addCriterion("defaultnum =", value, "defaultnum");
            return (Criteria) this;
        }

        public Criteria andDefaultnumNotEqualTo(Integer value) {
            addCriterion("defaultnum <>", value, "defaultnum");
            return (Criteria) this;
        }

        public Criteria andDefaultnumGreaterThan(Integer value) {
            addCriterion("defaultnum >", value, "defaultnum");
            return (Criteria) this;
        }

        public Criteria andDefaultnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("defaultnum >=", value, "defaultnum");
            return (Criteria) this;
        }

        public Criteria andDefaultnumLessThan(Integer value) {
            addCriterion("defaultnum <", value, "defaultnum");
            return (Criteria) this;
        }

        public Criteria andDefaultnumLessThanOrEqualTo(Integer value) {
            addCriterion("defaultnum <=", value, "defaultnum");
            return (Criteria) this;
        }

        public Criteria andDefaultnumIn(List<Integer> values) {
            addCriterion("defaultnum in", values, "defaultnum");
            return (Criteria) this;
        }

        public Criteria andDefaultnumNotIn(List<Integer> values) {
            addCriterion("defaultnum not in", values, "defaultnum");
            return (Criteria) this;
        }

        public Criteria andDefaultnumBetween(Integer value1, Integer value2) {
            addCriterion("defaultnum between", value1, value2, "defaultnum");
            return (Criteria) this;
        }

        public Criteria andDefaultnumNotBetween(Integer value1, Integer value2) {
            addCriterion("defaultnum not between", value1, value2, "defaultnum");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowIsNull() {
            addCriterion("threeyearrow is null");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowIsNotNull() {
            addCriterion("threeyearrow is not null");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowEqualTo(String value) {
            addCriterion("threeyearrow =", value, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowNotEqualTo(String value) {
            addCriterion("threeyearrow <>", value, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowGreaterThan(String value) {
            addCriterion("threeyearrow >", value, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowGreaterThanOrEqualTo(String value) {
            addCriterion("threeyearrow >=", value, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowLessThan(String value) {
            addCriterion("threeyearrow <", value, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowLessThanOrEqualTo(String value) {
            addCriterion("threeyearrow <=", value, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowLike(String value) {
            addCriterion("threeyearrow like", value, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowNotLike(String value) {
            addCriterion("threeyearrow not like", value, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowIn(List<String> values) {
            addCriterion("threeyearrow in", values, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowNotIn(List<String> values) {
            addCriterion("threeyearrow not in", values, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowBetween(String value1, String value2) {
            addCriterion("threeyearrow between", value1, value2, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andThreeyearrowNotBetween(String value1, String value2) {
            addCriterion("threeyearrow not between", value1, value2, "threeyearrow");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("priority is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("priority is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(String value) {
            addCriterion("priority =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(String value) {
            addCriterion("priority <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(String value) {
            addCriterion("priority >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(String value) {
            addCriterion("priority >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(String value) {
            addCriterion("priority <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(String value) {
            addCriterion("priority <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLike(String value) {
            addCriterion("priority like", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotLike(String value) {
            addCriterion("priority not like", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<String> values) {
            addCriterion("priority in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<String> values) {
            addCriterion("priority not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(String value1, String value2) {
            addCriterion("priority between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(String value1, String value2) {
            addCriterion("priority not between", value1, value2, "priority");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminset
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 02 21:20:45 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminset
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}