package com.backoffice.model;

public class Adminset {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminset.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminset.logimg
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String logimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminset.systemname
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String systemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminset.defaultnum
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private Integer defaultnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminset.threeyearrow
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String threeyearrow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminset.priority
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminset.id
     *
     * @return the value of adminset.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminset.id
     *
     * @param id the value for adminset.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminset.logimg
     *
     * @return the value of adminset.logimg
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getLogimg() {
        return logimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminset.logimg
     *
     * @param logimg the value for adminset.logimg
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setLogimg(String logimg) {
        this.logimg = logimg == null ? null : logimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminset.systemname
     *
     * @return the value of adminset.systemname
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getSystemname() {
        return systemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminset.systemname
     *
     * @param systemname the value for adminset.systemname
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setSystemname(String systemname) {
        this.systemname = systemname == null ? null : systemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminset.defaultnum
     *
     * @return the value of adminset.defaultnum
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public Integer getDefaultnum() {
        return defaultnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminset.defaultnum
     *
     * @param defaultnum the value for adminset.defaultnum
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setDefaultnum(Integer defaultnum) {
        this.defaultnum = defaultnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminset.threeyearrow
     *
     * @return the value of adminset.threeyearrow
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getThreeyearrow() {
        return threeyearrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminset.threeyearrow
     *
     * @param threeyearrow the value for adminset.threeyearrow
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setThreeyearrow(String threeyearrow) {
        this.threeyearrow = threeyearrow == null ? null : threeyearrow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminset.priority
     *
     * @return the value of adminset.priority
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminset.priority
     *
     * @param priority the value for adminset.priority
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setPriority(String priority) {
        this.priority = priority == null ? null : priority.trim();
    }

	@Override
	public String toString() {
		return "Adminset [id=" + id + ", logimg=" + logimg + ", systemname=" + systemname + ", defaultnum=" + defaultnum
				+ ", threeyearrow=" + threeyearrow + ", priority=" + priority + "]";
	}
    
}