package com.backoffice.model;

import java.util.Date;

public class Expert {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.name
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.sex
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.birth
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.title
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.title_level
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String titleLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.education
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.post
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.post_level
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String postLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.subject
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.candidate
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String candidate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.phone
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.email
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.institute
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String institute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.department
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.picture
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.status
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert.remarks
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.id
     *
     * @return the value of expert.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.id
     *
     * @param id the value for expert.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.name
     *
     * @return the value of expert.name
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.name
     *
     * @param name the value for expert.name
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.sex
     *
     * @return the value of expert.sex
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.sex
     *
     * @param sex the value for expert.sex
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.birth
     *
     * @return the value of expert.birth
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.birth
     *
     * @param birth the value for expert.birth
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.title
     *
     * @return the value of expert.title
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.title
     *
     * @param title the value for expert.title
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.title_level
     *
     * @return the value of expert.title_level
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getTitleLevel() {
        return titleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.title_level
     *
     * @param titleLevel the value for expert.title_level
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setTitleLevel(String titleLevel) {
        this.titleLevel = titleLevel == null ? null : titleLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.education
     *
     * @return the value of expert.education
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.education
     *
     * @param education the value for expert.education
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.post
     *
     * @return the value of expert.post
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.post
     *
     * @param post the value for expert.post
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.post_level
     *
     * @return the value of expert.post_level
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getPostLevel() {
        return postLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.post_level
     *
     * @param postLevel the value for expert.post_level
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setPostLevel(String postLevel) {
        this.postLevel = postLevel == null ? null : postLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.subject
     *
     * @return the value of expert.subject
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.subject
     *
     * @param subject the value for expert.subject
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.candidate
     *
     * @return the value of expert.candidate
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getCandidate() {
        return candidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.candidate
     *
     * @param candidate the value for expert.candidate
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setCandidate(String candidate) {
        this.candidate = candidate == null ? null : candidate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.phone
     *
     * @return the value of expert.phone
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.phone
     *
     * @param phone the value for expert.phone
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.email
     *
     * @return the value of expert.email
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.email
     *
     * @param email the value for expert.email
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.institute
     *
     * @return the value of expert.institute
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.institute
     *
     * @param institute the value for expert.institute
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.department
     *
     * @return the value of expert.department
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.department
     *
     * @param department the value for expert.department
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.picture
     *
     * @return the value of expert.picture
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.picture
     *
     * @param picture the value for expert.picture
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.status
     *
     * @return the value of expert.status
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.status
     *
     * @param status the value for expert.status
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert.remarks
     *
     * @return the value of expert.remarks
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert.remarks
     *
     * @param remarks the value for expert.remarks
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	@Override
	public String toString() {
		return "Expert [id=" + id + ", name=" + name + ", sex=" + sex + ", birth=" + birth + ", title=" + title
				+ ", titleLevel=" + titleLevel + ", education=" + education + ", post=" + post + ", postLevel="
				+ postLevel + ", subject=" + subject + ", candidate=" + candidate + ", phone=" + phone + ", email="
				+ email + ", institute=" + institute + ", department=" + department + ", picture=" + picture
				+ ", status=" + status + ", remarks=" + remarks + "]";
	}
    
}