package com.backoffice.model;

public class SubjectGroupExpertOperate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group_expert_operate.id
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group_expert_operate.subjectgroupid
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    private Integer subjectgroupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group_expert_operate.expertid
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    private Integer expertid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group_expert_operate.status
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group_expert_operate.id
     *
     * @return the value of subject_group_expert_operate.id
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group_expert_operate.id
     *
     * @param id the value for subject_group_expert_operate.id
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group_expert_operate.subjectgroupid
     *
     * @return the value of subject_group_expert_operate.subjectgroupid
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    public Integer getSubjectgroupid() {
        return subjectgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group_expert_operate.subjectgroupid
     *
     * @param subjectgroupid the value for subject_group_expert_operate.subjectgroupid
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    public void setSubjectgroupid(Integer subjectgroupid) {
        this.subjectgroupid = subjectgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group_expert_operate.expertid
     *
     * @return the value of subject_group_expert_operate.expertid
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    public Integer getExpertid() {
        return expertid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group_expert_operate.expertid
     *
     * @param expertid the value for subject_group_expert_operate.expertid
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    public void setExpertid(Integer expertid) {
        this.expertid = expertid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group_expert_operate.status
     *
     * @return the value of subject_group_expert_operate.status
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group_expert_operate.status
     *
     * @param status the value for subject_group_expert_operate.status
     *
     * @mbg.generated Sat Apr 20 15:43:23 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

	@Override
	public String toString() {
		return "SubjectGroupExpertOperate [id=" + id + ", subjectgroupid=" + subjectgroupid + ", expertid=" + expertid
				+ ", status=" + status + "]";
	}
    
}