package com.backoffice.model;

import java.util.ArrayList;
import java.util.List;

public class SubjectGroupExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public SubjectGroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSubSubjectIsNull() {
            addCriterion("sub_subject is null");
            return (Criteria) this;
        }

        public Criteria andSubSubjectIsNotNull() {
            addCriterion("sub_subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubSubjectEqualTo(String value) {
            addCriterion("sub_subject =", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectNotEqualTo(String value) {
            addCriterion("sub_subject <>", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectGreaterThan(String value) {
            addCriterion("sub_subject >", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("sub_subject >=", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectLessThan(String value) {
            addCriterion("sub_subject <", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectLessThanOrEqualTo(String value) {
            addCriterion("sub_subject <=", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectLike(String value) {
            addCriterion("sub_subject like", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectNotLike(String value) {
            addCriterion("sub_subject not like", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectIn(List<String> values) {
            addCriterion("sub_subject in", values, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectNotIn(List<String> values) {
            addCriterion("sub_subject not in", values, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectBetween(String value1, String value2) {
            addCriterion("sub_subject between", value1, value2, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectNotBetween(String value1, String value2) {
            addCriterion("sub_subject not between", value1, value2, "subSubject");
            return (Criteria) this;
        }

        public Criteria andExpertNumIsNull() {
            addCriterion("expert_num is null");
            return (Criteria) this;
        }

        public Criteria andExpertNumIsNotNull() {
            addCriterion("expert_num is not null");
            return (Criteria) this;
        }

        public Criteria andExpertNumEqualTo(String value) {
            addCriterion("expert_num =", value, "expertNum");
            return (Criteria) this;
        }

        public Criteria andExpertNumNotEqualTo(String value) {
            addCriterion("expert_num <>", value, "expertNum");
            return (Criteria) this;
        }

        public Criteria andExpertNumGreaterThan(String value) {
            addCriterion("expert_num >", value, "expertNum");
            return (Criteria) this;
        }

        public Criteria andExpertNumGreaterThanOrEqualTo(String value) {
            addCriterion("expert_num >=", value, "expertNum");
            return (Criteria) this;
        }

        public Criteria andExpertNumLessThan(String value) {
            addCriterion("expert_num <", value, "expertNum");
            return (Criteria) this;
        }

        public Criteria andExpertNumLessThanOrEqualTo(String value) {
            addCriterion("expert_num <=", value, "expertNum");
            return (Criteria) this;
        }

        public Criteria andExpertNumLike(String value) {
            addCriterion("expert_num like", value, "expertNum");
            return (Criteria) this;
        }

        public Criteria andExpertNumNotLike(String value) {
            addCriterion("expert_num not like", value, "expertNum");
            return (Criteria) this;
        }

        public Criteria andExpertNumIn(List<String> values) {
            addCriterion("expert_num in", values, "expertNum");
            return (Criteria) this;
        }

        public Criteria andExpertNumNotIn(List<String> values) {
            addCriterion("expert_num not in", values, "expertNum");
            return (Criteria) this;
        }

        public Criteria andExpertNumBetween(String value1, String value2) {
            addCriterion("expert_num between", value1, value2, "expertNum");
            return (Criteria) this;
        }

        public Criteria andExpertNumNotBetween(String value1, String value2) {
            addCriterion("expert_num not between", value1, value2, "expertNum");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subject_group
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 02 21:20:45 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subject_group
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}