package com.backoffice.model;

public class SubjectGroupCandidate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group_candidate.id
     *
     * @mbg.generated Sat Apr 06 14:54:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group_candidate.subjectid
     *
     * @mbg.generated Sat Apr 06 14:54:33 CST 2019
     */
    private Integer subjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group_candidate.candidateid
     *
     * @mbg.generated Sat Apr 06 14:54:33 CST 2019
     */
    private String candidateid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group_candidate.id
     *
     * @return the value of subject_group_candidate.id
     *
     * @mbg.generated Sat Apr 06 14:54:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group_candidate.id
     *
     * @param id the value for subject_group_candidate.id
     *
     * @mbg.generated Sat Apr 06 14:54:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group_candidate.subjectid
     *
     * @return the value of subject_group_candidate.subjectid
     *
     * @mbg.generated Sat Apr 06 14:54:33 CST 2019
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group_candidate.subjectid
     *
     * @param subjectid the value for subject_group_candidate.subjectid
     *
     * @mbg.generated Sat Apr 06 14:54:33 CST 2019
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group_candidate.candidateid
     *
     * @return the value of subject_group_candidate.candidateid
     *
     * @mbg.generated Sat Apr 06 14:54:33 CST 2019
     */
    public String getCandidateid() {
        return candidateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group_candidate.candidateid
     *
     * @param candidateid the value for subject_group_candidate.candidateid
     *
     * @mbg.generated Sat Apr 06 14:54:33 CST 2019
     */
    public void setCandidateid(String candidateid) {
        this.candidateid = candidateid == null ? null : candidateid.trim();
    }

	@Override
	public String toString() {
		return "SubjectGroupCandidate [id=" + id + ", subjectid=" + subjectid + ", candidateid=" + candidateid + "]";
	}
    
    
}