package com.backoffice.model;

public class SubjectGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group.name
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group.sub_subject
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String subSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group.expert_num
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String expertNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_group.remarks
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group.id
     *
     * @return the value of subject_group.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group.id
     *
     * @param id the value for subject_group.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group.name
     *
     * @return the value of subject_group.name
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group.name
     *
     * @param name the value for subject_group.name
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group.sub_subject
     *
     * @return the value of subject_group.sub_subject
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getSubSubject() {
        return subSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group.sub_subject
     *
     * @param subSubject the value for subject_group.sub_subject
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setSubSubject(String subSubject) {
        this.subSubject = subSubject == null ? null : subSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group.expert_num
     *
     * @return the value of subject_group.expert_num
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getExpertNum() {
        return expertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group.expert_num
     *
     * @param expertNum the value for subject_group.expert_num
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setExpertNum(String expertNum) {
        this.expertNum = expertNum == null ? null : expertNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_group.remarks
     *
     * @return the value of subject_group.remarks
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_group.remarks
     *
     * @param remarks the value for subject_group.remarks
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	@Override
	public String toString() {
		return "SubjectGroup [id=" + id + ", name=" + name + ", subSubject=" + subSubject + ", expertNum=" + expertNum
				+ ", remarks=" + remarks + "]";
	}
    
}