package com.backoffice.model;

public class Subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.subject_name
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String subjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.remarks
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.id
     *
     * @return the value of subject.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.id
     *
     * @param id the value for subject.id
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.subject_name
     *
     * @return the value of subject.subject_name
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.subject_name
     *
     * @param subjectName the value for subject.subject_name
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.remarks
     *
     * @return the value of subject.remarks
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.remarks
     *
     * @param remarks the value for subject.remarks
     *
     * @mbg.generated Tue Apr 02 21:20:45 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	@Override
	public String toString() {
		return "Subject [id=" + id + ", subjectName=" + subjectName + ", remarks=" + remarks + "]";
	}
    
}